apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"   # Sync Wave נמוכה → קודם כל יווצר
data:
  welcome-message: "Hello from ArgoCD Hooks!"
