apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # Sync Wave גבוהה יותר → אחרי ConfigMap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: nginx
        image: nginx:1.26
        ports:
        - containerPort: 80
        env:
        - name: WELCOME_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: welcome-message
