apiVersion: batch/v1
kind: Job
metadata:
  name: pre-sync-job
  annotations:
    argocd.argoproj.io/hook: PreSync   # הרצה לפני סנכרון שאר המשאבים
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "This runs before sync!"]
      restartPolicy: Never
